# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('ts', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SlackObject',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('object_type', models.CharField(max_length=64)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='slackmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackarchive.SlackObject'),
        ),
        migrations.AddField(
            model_name='slackmessage',
            name='slackuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackarchive.SlackUser'),
        ),
    ]
